In [ ]:
import numpy as np 
import pandas as pd 

**Importing the Data into pandas Data Frame**

In [ ]:
df = pd.read_csv('/content/fake_job_postings.csv')
df.head()

job_id  ... fraudulent
0       1  ...          0
1       2  ...          0
2       3  ...          0
3       4  ...          0
4       5  ...          0

[5 rows x 18 columns]

**Remove Unrelated Attributes**

In [ ]:
df.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [ ]:
df = df.drop(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function'], axis=1)

In [ ]:
df.head()

description  fraudulent
0  Food52, a fast-growing, James Beard Award-winn...           0
1  Organised - Focused - Vibrant - Awesome!Do you...           0
2  Our client, located in Houston, is actively se...           0
3  THE COMPANY: ESRI – Environmental Systems Rese...           0
4  JOB TITLE: Itemization Review ManagerLOCATION:...           0

**DropNa**

In [ ]:
df.dropna(inplace=True) 

**Change Cols Names**

In [ ]:
df.columns = ['data', 'labels']
df.head()

data  labels
0  Food52, a fast-growing, James Beard Award-winn...       0
1  Organised - Focused - Vibrant - Awesome!Do you...       0
2  Our client, located in Houston, is actively se...       0
3  THE COMPANY: ESRI – Environmental Systems Rese...       0
4  JOB TITLE: Itemization Review ManagerLOCATION:...       0

**Lowecasing All Letters**

In [ ]:
df['data'] = df['data'].str.lower()
df.data[0]

'food52, a fast-growing, james beard award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its new york city headquarters.reproducing and/or repackaging existing food52 content for a number of partner sites, such as huffington post, yahoo, buzzfeed, and more in their various content management systemsresearching blogs and websites for the provisions by food52 affiliate programassisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriessupporting with pr &amp; events when neededhelping with office administrative work, such as filing, mailing, and preparing for meetingsworking with developers to document bugs and suggest improvements to the sitesupporting the marketing and executive staff'

**Text Pre-processing**

In [ ]:
import nltk 

nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
df['data'][1]

"organised - focused - vibrant - awesome!do you have a passion for customer service? slick typing skills? maybe account management? ...and think administration is cooler than a polar bear on a jetski? then we need to hear you!\xa0we are the cloud video production service and opperating on a glodal level. yeah, it's pretty cool. serious about\xa0delivering a world class product and excellent customer service.our rapidly expanding business is looking for a talented project manager to manage the successful delivery of video projects, manage client communications and drive the production process. work with some of the coolest brands on the planet and learn from a global team that are representing nz is a huge way!we are entering the next growth stage of our business and growing quickly internationally. \xa0therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 seconds, the worlds cloud video production service -\xa0http://90

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
stemming = PorterStemmer()
stops = set(stopwords.words("english"))    
def identify_tokens(row):
    review = row
    tokens = nltk.word_tokenize(review)
    # taken only words (not punctuation)
    token_words = [w for w in tokens if w.isalpha()]
    meaningful_words = [w for w in token_words if not w in stops]
    stemmed_list = [stemming.stem(word) for word in meaningful_words]
    joined_words = (' '.join(stemmed_list))
    return joined_words

In [ ]:
df['processed'] = df['data'].apply(identify_tokens)

In [ ]:
df['processed'][1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product success team countri guarante video project succ

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
Y = df['labels'].to_numpy()

**TF-IDF Feature Extraction**

In [ ]:
tfidf = TfidfVectorizer(decode_error='ignore')
X = tfidf.fit_transform(df['processed'].values.astype('U'))
X.shape

(17879, 45546)

In [ ]:
df['processed'][17876]

'payrol account focu primarili payrol function approxim count employe addit individu assist variou task within account depart rapidli grow cut edg web develop ideal candid would payrol possess experi autonomi abl work minim supervis fulfil oblig fun open work environ candid must also possess expertis applic account principl practic provid support account process payrol outsourc payrol handl account analysi administr function relat resolv respond time inquiri benefit administr includ point contact third parti complet payrol gener account analysi journal perform intern payrol review ensur accuraci maintain employe personnel annual renew flexibl spend transit reimburs assist account team account payabl'

**Train/ Test Splitting**

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.3)

**Multi-Nomial Naive Bayes**

In [ ]:
modelNB = MultinomialNB()
modelNB.fit(xtrain,ytrain)

MultinomialNB()

In [ ]:
NBPreds = modelNB.predict(xtest)
print('Confusion Matrix')
print(confusion_matrix(ytest, NBPreds))

print('Classification Report')
print(classification_report(ytest, NBPreds))

print("Accuracy:",metrics.accuracy_score(ytest, NBPreds))
print("TNR:",metrics.precision_score(ytest, NBPreds))
print("NPV:",metrics.recall_score(ytest, NBPreds))

Confusion Matrix
[[5088   12]
 [ 263    1]]
Classification Report
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      5100
           1       0.08      0.00      0.01       264

    accuracy                           0.95      5364
   macro avg       0.51      0.50      0.49      5364
weighted avg       0.91      0.95      0.93      5364

Accuracy: 0.9487322893363161
TNR: 0.07692307692307693
NPV: 0.003787878787878788


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

**Support Vector Machine**

In [ ]:
clf = svm.SVC(kernel='linear') # Linear Kernel
clf.fit(xtrain,ytrain)

SVC(kernel='linear')

In [ ]:
SVMpred = clf.predict(xtest)

In [ ]:
print('Confusion Matrix')
print(confusion_matrix(ytest, SVMpred))
print('Classification Report')
print(classification_report(ytest, SVMpred))
print("Accuracy:",metrics.accuracy_score(ytest, SVMpred))
print("TNR:",metrics.precision_score(ytest, SVMpred))
print("NPV:",metrics.recall_score(ytest, SVMpred))

Confusion Matrix
[[5096    4]
 [ 155  109]]
Classification Report
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      5100
           1       0.96      0.41      0.58       264

    accuracy                           0.97      5364
   macro avg       0.97      0.71      0.78      5364
weighted avg       0.97      0.97      0.96      5364

Accuracy: 0.9703579418344519
TNR: 0.9646017699115044
NPV: 0.4128787878787879


**Decision Tree**

In [ ]:
DTC = DecisionTreeClassifier()
DTC = DTC.fit(xtrain,ytrain)
DTCPred = DTC.predict(xtest)

In [ ]:
print('Confusion Matrix')
print(confusion_matrix(ytest, DTCPred))
print('Classification Report')
print(classification_report(ytest, DTCPred))
print("Accuracy:",metrics.accuracy_score(ytest, DTCPred))
print("TNR:",metrics.precision_score(ytest, DTCPred))
print("NPV:",metrics.recall_score(ytest, DTCPred))

Confusion Matrix
[[5031   69]
 [  98  166]]
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      5100
           1       0.71      0.63      0.67       264

    accuracy                           0.97      5364
   macro avg       0.84      0.81      0.82      5364
weighted avg       0.97      0.97      0.97      5364

Accuracy: 0.9688665175242357
TNR: 0.7063829787234043
NPV: 0.6287878787878788


**K-Nearest Neighbors**

In [ ]:
KNN = KNeighborsClassifier(n_neighbors=3)
KNN.fit(xtrain,ytrain)
KNNPred= KNN.predict(xtest)

In [ ]:
print('Confusion Matrix')
print(confusion_matrix(ytest, KNNPred))
print('Classification Report')
print(classification_report(ytest, KNNPred))
print("Accuracy:",metrics.accuracy_score(ytest, KNNPred))
print("TNR:",metrics.precision_score(ytest, KNNPred))
print("NPV:",metrics.recall_score(ytest, KNNPred))

Confusion Matrix
[[5034   66]
 [  80  184]]
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      5100
           1       0.74      0.70      0.72       264

    accuracy                           0.97      5364
   macro avg       0.86      0.84      0.85      5364
weighted avg       0.97      0.97      0.97      5364

Accuracy: 0.9727815063385533
TNR: 0.736
NPV: 0.696969696969697


**Random Forest**

In [ ]:
RF=RandomForestClassifier(n_estimators=100) #default number of trees in the forest model 
RF.fit(xtrain,ytrain)
RFPred=RF.predict(xtest)
print('Confusion Matrix')
print(confusion_matrix(ytest, RFPred))
print('Classification Report')
print(classification_report(ytest, RFPred))
print("Accuracy:",metrics.accuracy_score(ytest, RFPred))
print("TNR:",metrics.precision_score(ytest, RFPred))
print("NPV:",metrics.recall_score(ytest, RFPred))

Confusion Matrix
[[5097    3]
 [ 122  142]]
Classification Report
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      5100
           1       0.98      0.54      0.69       264

    accuracy                           0.98      5364
   macro avg       0.98      0.77      0.84      5364
weighted avg       0.98      0.98      0.97      5364

Accuracy: 0.976696495152871
TNR: 0.9793103448275862
NPV: 0.5378787878787878


#Max Voting

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.ensemble import VotingClassifier


In [ ]:
# group / ensemble of models
estimator = []
estimator.append(('DT', DecisionTreeClassifier()))
estimator.append(('SVC', svm.SVC(kernel='linear')))
estimator.append(('KNN', KNeighborsClassifier(n_neighbors=3)))
estimator.append(('NB', MultinomialNB()))
estimator.append(('RF', RandomForestClassifier(n_estimators=100)))

# Voting Classifier with hard voting
vot_hard = VotingClassifier(estimators = estimator, voting ='hard')
vot_hard.fit(xtrain, ytrain)
y_pred = vot_hard.predict(xtest)
# using accuracy_score metric to predict accuracy
score = accuracy_score(ytest, y_pred)
print("Score:",score)

Score: 0.977255779269202


#AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(random_state=1)
model.fit(xtrain, ytrain)
model.score(xtest,ytest)

0.9608501118568232

#GBM

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
model= GradientBoostingClassifier(learning_rate=0.01,random_state=1)
model.fit(xtrain, ytrain)
model.score(xtest,ytest)

0.9563758389261745

#XGB

In [ ]:
import xgboost as xgb
model=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
model.fit(xtrain, ytrain)
model.score(xtest,ytest)

0.9602908277404921

#Light GB

In [ ]:
import lightgbm as lgb
train_data=lgb.Dataset(xtrain,label=ytrain)
#define parameters
params = {'learning_rate':0.001}
model= lgb.train(params, train_data, 100) 
y_pred=model.predict(xtest)
for i in range(0,185):
   if y_pred[i]>=0.5: 
     y_pred[i]=1
else: 
   y_pred[i]=0

In [ ]:
import lightgbm as lgb
train_data=lgb.Dataset(xtrain,label=ytrain)
params = {'learning_rate':0.001}
model= lgb.train(params, train_data, 100)
from sklearn.metrics import mean_squared_error
rmse=mean_squared_error(y_pred,ytest)**0.5

In [ ]:
rmse

0.21001959355973449